### ISSUE TITLE
你好，怎么解决使用cache-aside时，cache层和repo层耦合太紧的问题呢？

### ISSUE THREAD

**Issue by xbpk3t** [alicfeng/TeamStandard#1]
比方说，cache-aside需要先判断某个key是否存在，这部分东西如果在repo层里处理的话，repo层需要完整的key，而redis的key，我现在只放在cache层里，所以，应该怎么解决呢？

**Comment by xbpk3t** [comment]
临时的解决方案是，在cache层的每个类里都加入几个方法用来判断对应key是否存在，但是感觉有点繁琐，所以这里有什么最佳实践吗

**Comment by alicfeng** [comment]
可以使用Callback来解决每次加入几个方法用来判断对应key是否存在，在 `Laravel` 框架中对于缓存的使用是已经封装了的,像一般常用的cache，我一般会在 `repository` 基类封装好，只需要传入指定的 `model` 即可，下面的没有封装的一般使用
```php
   public function list()
    {
        return Cache::remember(CacheKey::ALGO_LIST, self::CACHE_EXPIRE,function () {
                return Model::query()->get();
       });
    }
```
不知道我理解的是否你是表达的疑问?

**Comment by xbpk3t** [comment]
感谢回复，但是Cache::remember()只适用于字符串吧，是说在底层模仿这个方法，自己封装其他数据类型的cache-aisde方法吗
